version: 2

project_name: judgekit

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: judgekit
    env:
      - CGO_ENABLED=0
    main: ./cmd/judgekit
    binary: judgekit
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^diary:'

# modelines, feel free to remove those if you don't want/use them:
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
